package: ydeploy
version: '1.0-beta3'
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum/

requires:
    php: ^7.0
    redaxo: ^5.5

conflicts:
    packages:
        developer: '<3.7'

console_commands:
    ydeploy:diff: rex_ydeploy_command_diff
    ydeploy:migrate: rex_ydeploy_command_migrate

pages:
    system/ydeploy:
        title: YDeploy

config:
    fixtures:
        tables:
            config:
                - { namespace: core }
                - { namespace: mblock }
                - { namespace: media_manager }
                - { namespace: mform }
                - { namespace: sprog }
            markitup_profiles: ~
            media_manager_type: ~
            media_manager_type_effect: ~
            metainfo_field: ~
            metainfo_type: ~
            module_action: ~
            redactor2_profiles: ~
            yform_field: ~
            yform_table: ~
    protected_pages:
        install: ~
        markitup: ~
        media_manager: ~
        metainfo: ~
        modules: ~
        packages: ~
        redactor2: ~
        templates: ~
        yform/manager:
            - table_edit
            - table_migrate
            - tableset_import
            - table_field
