package: ydeploy
version: '2.0.0-dev'
author: Gregor Harlan
supportpage: https://github.com/yakamara/ydeploy

requires:
    php: '>=8.1'
    redaxo: ^5.13

conflicts:
    packages:
        developer: '<3.7'

console_commands:
    ydeploy:diff: rex_ydeploy_command_diff
    ydeploy:migrate: rex_ydeploy_command_migrate

pages:
    system/ydeploy:
        title: YDeploy
        pjax: false

config:
    fixtures:
        tables:
            config:
                - { namespace: core }
                - { namespace: mblock }
                - { namespace: media_manager }
                - { namespace: mform }
                - { namespace: rexstan }
                - { namespace: sprog }
            markitup_profiles: ~
            media_manager_type: ~
            media_manager_type_effect: ~
            metainfo_field: ~
            metainfo_type: ~
            module_action: ~
            redactor_profile: ~
            redactor2_profiles: ~
            yform_field: ~
            yform_table: ~
    protected_pages:
        install: ~
        markitup: ~
        media_manager: ~
        metainfo: ~
        modules: ~
        packages: ~
        redactor: ~
        redactor2: ~
        rexstan: ~
        templates: ~
        yform:
            setup: ~
            docs: ~
            manager:
                - table_edit
                - table_migrate
                - tableset_import
                - table_field

installer_ignore:
    - .github
    - .tools
    - .gitignore
    - .php-cs-fixer.cache
    - .php-cs-fixer.dist.php
    - vendor
