package: ydeploy
version: '1.0-beta1'
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum/

requires:
    redaxo: ^5.5

config:
    fixtures:
        tables:
            config:
                - { namespace: core }
                - { namespace: mblock }
                - { namespace: media_manager }
                - { namespace: mform }
                - { namespace: sprog }
            markitup_profiles: ~
            media_manager_type: ~
            media_manager_type_effect: ~
            metainfo_field: ~
            metainfo_type: ~
            module_action: ~
            redactor2_profiles: ~
            yform_field: ~
            yform_table: ~

console_commands:
    ydeploy:diff: rex_ydeploy_command_diff
    ydeploy:migrate: rex_ydeploy_command_migrate
